export enum ServiceType {
    DESIGN_GRAFICO,
    MARKETING_DIGITAL,
    REDACAO_TRADUCAO,
    VIDEO_ANIMACAO,
    MUSICA_AUDIO,
    PROGRAMACAO_TECNOLOGIA,
    FOTOGRAFIA,
    NEGOCIOS,
    SERVICOS_IA
}